### ISSUE TITLE
can't load package: package github.com/msprev/fzf-bibtex

### ISSUE THREAD

**Issue by remembertoremind** [msprev/fzf-bibtex#12]
Hi! I installed fzf, bibtool and go. However, the follow instructions `go get github.com/msprev/fzf-bibtex` gave me this error
```
can't load package: package github.com/msprev/fzf-bibtex: no Go files in /home/chansen/go/src/github.com/msprev/fzf-bibtex
```

I added the first funtion to vimrc and pressed leader c, which brings up an empty fzf. When pressing enter with nothing selected in fzf-bibtex the following is pasted in my document `/bin/bash: bibtex-cite: command not found`. However, the go-commands from the installation worked fine.

EDIT: I'm on arch btw

**Comment by msprev** [comment]
Can you try running `go get github.com/msprev/fzf-bibtex/cmd/bibtex-ls` first, and then run `go install` on all the commands, as per the installation instructions?

**Comment by remembertoremind** [comment]
That worked. I no longer get the error in vim and fzf-bibtex start as expected. However, there is still no content in fzf when it starts. I don't know how to get more information or troubleshoot unfortunately :/

**Comment by msprev** [comment]
Do you want to test it by running it on your bibliography file on the command line as described in the readme?

To use it in vim, you need to make sure these environment variables are set:

```
let $FZF_BIBTEX_CACHEDIR = 'PATH-TO-CACHE-DIR'
let $FZF_BIBTEX_SOURCES = 'PATH-TO-BIBTEX-FILE'
```

**Comment by msprev** [comment]
I'm closing the issue as I haven't heard anything further, and I'm assuming that you've got it working inside vim. Reopen the issue if this is not the case.
