### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by mathematicalmichael** [msprev/fzf-bibtex#18]
checked #12 and ran all instructions as per the README. I got no responses after any of the commands (go get / go install), and the software doesn't appear to be installed at all. (I installed all three dependencies with brew as well)

**Comment by msprev** [comment]
Are you sure the binaries that Go builds are in your path? 

Test this by typing `go env` in the terminal. Look at the `GOPATH` entry in the data listed. Go to the `bin` subdirectory of whatever location is listed. Are the binaries there?

Now type `echo $PATH` in the terminal. You path must include this `bin` directory if you want to access the binaries without specifying their full path on the command line. If you are using vim, then either you can (a) modify $PATH to include this directory; or (b) modify the example vimscript to give the full path to each executable in the `system(...)` statement. 

Let me know if this resolves the problem (note that this is a general property of any Go install, not peculiar to fzf-bibtex).

**Comment by msprev** [comment]
I haven't heard back, so I'm guessing that this issue should be closed? Please let me know if it hasn't been resolved.

**Comment by mathematicalmichael** [comment]
Oh, my bad! Thank you for pinging me again. Just saw this email (wish github had a better homescreen for notifs). Ill test it today and follow up!

**Comment by mathematicalmichael** [comment]
The binaries are inside GOPATH
PATH didn’t know of them, though. 
after adding them, bibtex-ls appears to now work! Thanks so much

**Comment by msprev** [comment]
Excellent! I'm delighted to hear this. I'm guessing that a similar PATH issue was responsible for https://github.com/msprev/fzf-bibtex/issues/12 too.
