### ISSUE TITLE
bibtex-cite appends % to the key

### ISSUE THREAD

**Issue by gerstorfer** [msprev/fzf-bibtex#19]
bibtex-cite appends an unwanted `%` to the key. This happens even on a fresh installation, doing only:
 ```{.bash}
$ echo @sprevak | bibtex-cite
 @sprevak%
```

**Comment by msprev** [comment]
I can't reproduce this. I think that the "%" is your shell's representation of a newline character. When I run the command I just get

```
@sprevak⏎ 
```

which is my shell's way of representing that the output is terminated with a newline. 

You could try `echo @sprevak | bibtex-cite | more` to see if you still get the '%' sign?

**Comment by gerstorfer** [comment]
I think you might be right. It was a `zsh` *feature* I wasn't aware of. Sorry to bother you with my late night mystery problems.

**Comment by msprev** [comment]
Great -- good to know!
