### ISSUE TITLE
Remove @-character from citations

### ISSUE THREAD

**Issue by NicolaiRuckel** [msprev/fzf-bibtex#21]
I use @ashwinvis's code from the [Vim integration](https://github.com/msprev/fzf-bibtex#vim-integration) section but `bibtex-ls` always prefixes my citation keys with an @. This means when I type `\cite{@@` and then choose the correct reference I get `\cite{@citation-key}` and have to change it to `\cite{citation-key}` every time. Is there a way to do this automatically?

**Comment by NicolaiRuckel** [comment]
I realized there is already a pull request that added this functionality with `bibtex-cite`'s `-prefix` flag.

**Comment by msprev** [comment]
Absolutely, this has already been implemented in the latest version. 

You need to customise your citation format by [adding parameters to your call to `bibtex-cite`](https://github.com/msprev/fzf-bibtex#bibtex-cite).

```
    let r=system('bibtex-cite -prefix="\cite{" -postfix="}" -separator=", " ', a:lines)
```

Make sure you pull and compile the latest version before trying this.
