### ISSUE TITLE
Support biblatex-sbl

### ISSUE THREAD

**Issue by folofjc** [msprev/fzf-bibtex#30]
`biblatex-sbl` (https://github.com/dcpurton/biblatex-sbl) adds some new entry types for bib files:
- `ancienttext`
- `classictext`
- `mvcommentary`
- `incommentary`
- `lexicon`
- `mvlexicon`
- `inlexicon`
- `series`

**Comment by msprev** [comment]
can you briefly summarise how fzf-bibtex currently handles these entries? Are they ignored in the listing of entries?

**Comment by folofjc** [comment]
`bibtool` throws an error on each entry, and then none of the cross references work with them. They do not exist in the output file from `bibtool`. As long as they are in the `rsc` file, they show up in the output of bibtool.

**Comment by msprev** [comment]
I'm happy to merge this as it seems to be a good use case.
