### ISSUE TITLE
Both `<leader>c` and `@@` put the citation to the right

### ISSUE THREAD

**Issue by folofjc** [msprev/fzf-bibtex#33]
If I am in normal mode and do `<leader>c`, it puts the citation to the right of the cursor. This might be intentional.

However, in insert mode, when I do `@@` it also puts it one space to the right, which is incorrect. It should go where the cursor is.

**Comment by msprev** [comment]
I'm not sure I see the issue here. These commands behave as I expect... 

- `@@` inserts citation at the cursor point (it behaves like paste `c-r*` in vim insert mode); 
- `<leader>c` inserts citation immediately after the cursor point (it behaves exactly like `p` in vim normal mode)

This seems the most natural and vim-like behaviour to me. If you don't like it, it's easy to change it by editing `bibtex_cite_sink` etc. functions in your vimrc. 

If you think there is a more vim-like alternative of these commands, reopen this issue with a specific proposal.

**Comment by folofjc** [comment]
> * `@@` inserts citation at the cursor point (it behaves like paste `c-r*` in vim insert mode);

It does **not** do this, that was my point. As an example, if I have something like: `[cite1][cite2][][cite4]` and I am trying to insert `cite3` in between the brackets. I go in insert mode, and I put my cursor between the brackets, and I type `@@` and search for cite 3 and hit `Enter`, then it does this: `[cite1][cite2][]cite3[cite4]`.

It places it is one spot to the right of the cursor. This is not the most natural and vim-like behavior, IMO.

**Comment by folofjc** [comment]
> * `<leader>c` inserts citation immediately after the cursor point (it behaves exactly like `p` in vim normal mode)

This I can see as intended. I expected it to do more like `P` in normal mode, but that isn't necessarily "more" vim-like.

**Comment by msprev** [comment]
> > * `@@` inserts citation at the cursor point (it behaves like paste `c-r*` in vim insert mode);
> 
> It does **not** do this, that was my point. As an example, if I have something like: `[cite1][cite2][][cite4]` and I am trying to insert `cite3` in between the brackets. I go in insert mode, and I put my cursor between the brackets, and I type `@@` and search for cite 3 and hit `Enter`, then it does this: `[cite1][cite2][]cite3[cite4]`.
> 
> It places it is one spot to the right of the cursor. This is not the most natural and vim-like behavior, IMO.

I cannot reproduce this behaviour on my version. I'm not sure why you are seeing it. `@@` behaves exactly as described in my initial post. If the cursor (`|`) is placed in `[cite1][cite2][|][cite4]` and `@@` is pressed, it produces `[cite1][cite2][cite3|][cite4]`.

If other users are seeing this issue, I'll reopen it, but it may be worth doing some debugging on your vimrc to see if some configuration issue local to your install.
