### ISSUE TITLE
[help] Modification and install question

### ISSUE THREAD

**Issue by folofjc** [msprev/fzf-bibtex#34]
In reference to #33, I was trying to edit the code and then test, but I am unsure how to install once I have made changes. Would you mind updating the README so that it gives instruction for how to install a local clone in go? Maybe it is super easy and I should already know, but if it is as easy as `go install <clone location>@latest` then that should be an easy fix in the README.

**Comment by msprev** [comment]
This is out of scope for the fzf-bibtex readme. There are lots of resources online that explain how to work with local copies of Go modules, e.g. https://teivah.medium.com/how-to-test-a-local-branch-with-go-mod-54df087fc9cc

**Comment by folofjc** [comment]
But that just shows how to test a _module_ that has changed. It doesn't specify how to change `bar` itself.
