### ISSUE TITLE
bibtex-* commands not exported

### ISSUE THREAD

**Issue by dloewenstein** [msprev/fzf-bibtex#9]
Thank you for awesome work!

Just one thing, I followed the installation instructions (I'm running ubuntu 18.04 under WSL) but the go command where not exported. Had to add make the following changes to vimrc to make them work

let $FZF_BIBTEX_CACHEDIR = 'PATH-TO-CACHE-DIR'
let $FZF_BIBTEX_SOURCES = 'PATH-TO-BIBTEX-FILE'

function! s:bibtex_cite_sink(lines)
    let r=system("~/go/bin/bibtex-cite ", a:lines) "inserted filepath
    execute ':normal! i' . r
endfunction

function! s:bibtex_markdown_sink(lines)
    let r=system("~/go/bin/bibtex-markdown ", a:lines) "inserted filepath
    execute ':normal! i' . r
endfunction

nnoremap <leader>c :call fzf#run({
                        \ 'source': '~/go/bin/bibtex-ls', "inserted filepath
                        \ 'sink*': function('<sid>bibtex_cite_sink'),
                        \ 'up': '40%',
                        \ 'options': '--ansi --layout=reverse-list --multi --prompt "Cite> "'})<CR>

nnoremap <leader>m :call fzf#run({
                        \ 'source': '~/go/bin/bibtex-ls', "inserted filepath
                        \ 'sink*': function('<sid>bibtex_markdown_sink'),
                        \ 'up': '40%',
                        \ 'options': '--ansi --layout=reverse-list --multi --prompt "Markdown> "'})<CR>

**Comment by msprev** [comment]
Thanks -- this looks like the relevant commands were not in the system file path in your case... I'll modify the docs to highlight this possibility.
